### ISSUE TITLE
Escape hatches on network primitives

### ISSUE THREAD

**Issue by vorner** [rustasync/runtime#113]
The API surface of the network primitives here (eg. `TcpListener`) is somewhat limited (understandably). However, the standard library supports things like `FromRawFd`, other async libraries support things like `from_std` or `connect_std` (in tokio, though hidden from docs).

Because, eventually, one runs into needs that are not covered by the basic API and needs to go to either things like the net2 crate, or directly calling stuff like setsockopt (often *before* the socket is connected) to achieve them. Such circumstances include, for example:
* Need to set local IP address for client TCP socket.
* Setting `REUSE_PORT` option to be able to scale across multiple processes or threads.

Would it be possible to include such escape hatches here too?

**Comment by yoshuawuyts** [comment]
@vorner hey! -- this library is not actively under development anymore, and most of the team has moved onto building `async-std` instead. We've been able to get a lot further there than we did here; and among other things we have a working [`TcpListener::FromRawFd`](https://docs.rs/async-std/0.99.7/async_std/net/struct.TcpListener.html#impl-FromRawFd) implementation :sparkles:.

We'll probably put up a notice on the repo soon directing people to use async-std and tokio respectively.

**Comment by vorner** [comment]
Thanks for letting me know, this means one less „backend“ to support for me. I know about the async-std :-).

As for the notice ‒ that would definitely help, knowing the state. Would it also be possible to release a version with it, so such notice gets onto crates.io and docs.rs?

**Comment by yoshuawuyts** [comment]
@vorner yep; will do!
