### ISSUE TITLE
Consider renaming runtime-native

### ISSUE THREAD

**Issue by seanmonstar** [rustasync/runtime#15]
As noted in this comment on [/r/rust](https://www.reddit.com/r/rust/comments/bdy9y7/runtime/el2ryjc/):

> Since the native runtime is also not really more native than Tokio, calling it the SimpleRuntime or ReducedRuntime might give a better indication to users about what to expect from it.

I felt similar when I first saw the name. I'd assume "native" to mean something provide by the OS. Perhaps it should be renamed to something else?

**Comment by yoshuawuyts** [comment]
Hi, thanks for opening this issue! The naming of our crates is currently not up for consideration. We're in active development, and it's still early days for the project as a whole

We feel comfortable with the naming that we've chosen, even if things might change even if things change as we mature as a project, and will stick to our choices for the foreseeable future.
