### ISSUE TITLE
Feature request: runtime-tokio-singlethreaded

### ISSUE THREAD

**Issue by vi** [rustasync/runtime#2]
**Choose one:**  feature request.

## Expected Behavior

One of runtimes from the list to choose provies fully single-threaded (no `clone` syscall) application (unless I manually call `std::thread::spawn`, of course).

## Current Behavior

There seems to be no such thing in the list.

## Possible Solution

Add a runtime based on `tokio::runtime::current_thread`.

## Context

Reasons to be singlethreaded:

* To economize OS resources when not doing highload.
* To use non-threadsafe libraries with `Rc<RefCell>`s inside
* To debug applications more easily before going multithreaded
* To use async in environment without OS threads
* To embed code into larger apps which may become broken if the code suddenly spawns a thread
* To speed up by removing `futex` (synchronisation) cost on single core systems.

**Comment by yoshuawuyts** [comment]
@vi thanks for filing this. Implemented in #3, and released as `runtime-tokio@0.3.0-alpha.2` :tada:
