### ISSUE TITLE
How to call an async function from a normal function?

### ISSUE THREAD

**Issue by ufosky** [rustasync/runtime#43]
I found if I use an async function, the other codes using this function must implement as an async function. Is there some suggestion for using async function from normal function?

**Comment by zeroqn** [comment]
Either use
```rust
futures::executor::block_on(your_future)
```
or 
```rust
use runtime_tokio::Tokio;

fn main() {
    runtime::raw::enter(Tokio, your_future);
}
```
If you want to run it using this crate.

**Comment by yoshuawuyts** [comment]
We could / should probably expose some convenience methods here, so nobody ever needs to use `runtime::raw` directly:

### with `#[runtime::main]`
```rust
runtime::task::block_on(async move {
    /* code goes here */
})
```

### without `#[runtime::main]`
```rust
runtime_tokio::block_on(async move {
    /* code goes here */
})
```

**Comment by yoshuawuyts** [comment]
Related: https://github.com/rustasync/runtime/issues/42
