### ISSUE TITLE
Provide a more useful synopsis of what this library does in the README

### ISSUE THREAD

**Issue by jimmycuadra** [rustasync/runtime#56]
I've seen this library linked from other places a few times, and every time I've looked at it, I haven't been able to understand why I would use it for anything. Not until [this comment](https://github.com/mitsuhiko/redis-rs/issues/184#issuecomment-504510053) did I understand that it's *an abstraction over future executors* so that libraries that do async networking don't have to depend on Tokio directly. It would be very useful to explain this succinctly at the top of the README, because "empowering everyone to build asynchronous software" is not a useful description, and the current about section of the README speaks in broad generalities without explaining what the library *actually is*.

**Comment by yoshuawuyts** [comment]
@jimmycuadra thanks for opening this issue -- that's great feedback! We'll have to think a bit on how to adjust the messaging to better communicate this in the context of the rest of the README (it's quite long). But hearing you loud and clear, and we should do better!

**Comment by apiraino** [comment]
Hello! Just stumbled on this issue.

Yes, it's not easy to quickly grasp what Runtime is and does (me being a newbie figuring out the async Rust ecosystem). While you figure out something better, would you @yoshuawuyts accept this as a "30 Second Elevator Pitch"?

---8x---8x---8x---8x---8x---8x---
[Runtime] is an abstraction over future executors, a very thin wrapper over [tokio](https://tokio.rs/) or [romio](https://github.com/withoutboats/romio) (the reactor) + [juliex](https://github.com/withoutboats/juliex) (the executor), see the section ["Runtimes"](https://github.com/rustasync/runtime#runtimes).
---8x---8x---8x---8x---8x---8x---
