### ISSUE TITLE
runtime doesn't work with `default-features = false`

### ISSUE THREAD

**Issue by Nemo157** [rustasync/runtime#57]
Trying to compile a crate that uses `runtime` with `default-features = false` gives an error from the macro:

```
error[E0433]: failed to resolve: could not find `native` in `runtime`
 --> src/main.rs:5:1
  |
5 | #[runtime::main]
  | ^^^^^^^^^^^^^^^^ could not find `native` in `runtime`
```

**Comment by yoshuawuyts** [comment]
Ah yeah, that means you'll need to pass a custom runtime into the macro:

```rust
#[runtime::main(runtime_native::Runtime]
async fn main {}
```

We can probably add a feature to `runtime-attributes` that changes the macro impl if default features are disabled. Though that might have some odd interactions with #27.

Perhaps the more low-hanging fruit is to better document the features, and explain what they do. I don't believe we're properly documenting them yet.

**Comment by Nemo157** [comment]
> We can probably add a feature to `runtime-attributes` that changes the macro impl if default features are disabled. Though that might have some odd interactions with #27.

That was sort of my thinking as well. `#[runtime::main]` with `default-features = false` could just

```rust
panic!("You must manually select a runtime, or enable `some-feature` to have `runtime` select a default one for you")
```
