### ISSUE TITLE
impl Sync for UdpSocket

### ISSUE THREAD

**Issue by xofyarg** [rustasync/runtime#62]
`UdpSocket` doesn't implement `Sync`, which makes it hard to build a server that potentially share the socket between futures/threads.

**Comment by yoshuawuyts** [comment]
@xofyarg this seems like a reasonable request, and agree we should add a `Sync` bound to `UdpSocket`! Would you be interested in filing a patch for that? The relevant code is [here](https://github.com/rustasync/runtime/blob/master/runtime-raw/src/udp.rs#L8).
