### ISSUE TITLE
Async DNS resolution 

### ISSUE THREAD

**Issue by sbstp** [rustasync/runtime#63]
Hi. I've been maintaining a small crate named [`tokio-dns-unofficial`](https://github.com/sbstp/tokio-dns) which implements a really basic async DNS resolver. I'm trying to figure out how this crate should transition to the `std::future` era.

I quickly looked at the API and I noticed that DNS resolution seems to be blocking at the moment, `.to_socket_addrs()` is used and it could perform a blocking DNS request. I'd like to know how you envision DNS resolution for this crate. Should it be implemented here or in one of the lower-level runtimes?

It might also cause breakage if we add async DNS resolution to some functions which do not return a future currently.

**Comment by yoshuawuyts** [comment]
Hi, thanks for opening this issue!

Hah, so it feels like I may be about to learn something new here today. I was under the impression that[`to_socket_addrs`](https://doc.rust-lang.org/std/net/trait.ToSocketAddrs.html#tymethod.to_socket_addrs) would only be used to convert from one trait into another. Similar to how `Into` works; not necessarily bound to any networking code. But from what you're saying it sounds like that may not be the case here? I'm interested in how this works!

I was under the assumption that DNS is something that would work over either TCP, UDP, or even HTTPS. Which means it should probably be a crate that's built on top of Runtime, similar to how the crate is currently built on top of Tokio directly.

**Comment by sbstp** [comment]
Yeah, if you look at the docs for `to_socket_addrs()`, it says

> Converts this object to an iterator of resolved SocketAddrs.
> The returned iterator may not actually yield any values depending on the outcome of any resolution performed.
> **Note that this function may block the current thread while resolution is performed.**

If a hostname is used, i.e. "github.com:80", it will perform a DNS lookup using libc in order to produce an iterator of SocketAddr which contain an IP and a port.

I've talked a bit with the tokio author about this [here](https://github.com/tokio-rs/tokio/issues/343#issuecomment-505518178).

**Comment by yoshuawuyts** [comment]
@sbstp thanks for the explanation, I didn't know that.

Yeah, it definitely seems like we ought to implement a trait for this. Do you have any proposals on how you think we should approach this?

**Comment by sbstp** [comment]
I created a trait named [ToEndpoint](https://docs.rs/tokio-dns-unofficial/0.4.0/tokio_dns/trait.ToEndpoint.html) which is a copy of `ToSocketAddrs` but without blocking resolution. It's a good starting point. It needs to be paired with an async resolver library, my library provides a very basic one, but a better one should be implemented using c-ares, getdns or trustdns.
