### ISSUE TITLE
Why `Unpin` is required for `time::FutureExt`?

### ISSUE THREAD

**Issue by uHOOCCOOHu** [rustasync/runtime#65]
It seems not necessary since the `Future` is just a normal field of `Timeout`, according to [the docs of `std::pin`](https://doc.rust-lang.org/stable/std/pin/index.html#projections-and-structural-pinning).

`Unpin` requirement makes it hard to set timeout for `async fn`.

**Comment by yoshuawuyts** [comment]
@uHOOCCOOHu I have to admit I'm not as comfortable with pin semantics as I wish I was. If you suspect this can be removed & it makes life easier, we'd definitely welcome a patch to do so!

We definitely care a lot about allowing `async fn` timeouts! (:

**Comment by uHOOCCOOHu** [comment]
I'm quite sure that `F: Unpin` is not required for `time::Timeout` (and so do `TimeoutAsyncRead` and `TimeoutStream`), so the bound in `time::FutureExt` can be also removed.

Sadly, if so, the `poll()` method seems impossible to write without `unsafe` (required for pinning projection). Since we have `#![deny(unsafe_code)]`, I'm not sure if it is acceptable.

**Comment by sdroege** [comment]
Until there are more `Pin` helper functions, I don't think `#![deny(unsafe_code)]` is achievable for any project implementing futures manually unless you box everything and require `Unpin` on everything.
