### ISSUE TITLE
Consider adding blocking interop

### ISSUE THREAD

**Issue by rschmukler** [rustasync/runtime#81]
Currently tokio has support for relatively easily inter-op with blocking code. It would be nice if we could do the same thing. I think we might be able to improve on the ergonomics of Tokio's API by doing away with the `poll_fn` intermediary and instead allow just providing a `FnOnce` directly. 

Eg:

```rust
#[runtime::main]
async fn main() {
  runtime::blocking(|| {
    println!("Look how slow I am!");
  }).await;
})
```

Here is a link to the [relevant documentation of Tokio](https://docs.rs/tokio-threadpool/0.1.15/tokio_threadpool/fn.blocking.html). Some questions would need to be answered as to what we think the right max number of workers is for blocking operations. 

If there is interest in this, I could see about submitting a first-draft PR for consideration.

**Comment by rschmukler** [comment]
Just pining on here again. Happy to submit a PR but would like confirmation of buy-in before I do the work.

cc @yoshuawuyts

**Comment by leo60228** [comment]
You can implement this yourself on top of `futures`, this isn't tied to the async runtime:

```rust
use futures::channel::oneshot;
use std::thread;

let (tx, rx) = oneshot::channel();

thread::spawn(move || {
    info!("discord started");
    tx.send(Err(())).expect("couldn't send completion message");
});

rx.await.expect("completion sender unexpectedly dropped (did thread unwind?)")
```

**Comment by rschmukler** [comment]
@leo60228 I could be mistaking but I believe the `blocking` in tokio's runtime is actually taking care of managing a threadpool for running blocking closures for you, not just synchronizing the communication
