### ISSUE TITLE
Is chat link broken ? 

### ISSUE THREAD

**Issue by Gozala** [rustasync/runtime#82]
This is what I see when I follow the link to chat 

<img width="1007" alt="image" src="https://user-images.githubusercontent.com/21236/62811269-ef691900-bab5-11e9-979f-e0c9a0084e78.png">

**Comment by Gozala** [comment]
Turns out link works after going through the invite https://discordapp.com/invite/rust-lang

**Comment by yoshuawuyts** [comment]
@Gozala thanks for bringing this up. Sorry we didn't catch this sooner. Wrote a fix for this in #84!
